<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = new Product();
        $products->name = "white T-shirt";
        $products->description = "awesome white T-shirt";
        $products->price = "49.90";
        $products->quantity = "9";
        $products->category = "shirt";
        $products->type = "man";
        $products->image = "product1.webp";
        $products->save();
        $products = new Product();
        $products->name = "Red T-shirt";
        $products->description = "awesome Red T-shirt";
        $products->price = "69.99";
        $products->quantity = "2";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product2.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product3.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product4.webp";
        $products->save();$products = new Product();
        $products->name = "white T-shirt";
        $products->description = "awesome white T-shirt";
        $products->price = "49.90";
        $products->quantity = "9";
        $products->category = "shirt";
        $products->type = "man";
        $products->image = "product1.webp";
        $products->save();
        $products = new Product();
        $products->name = "Red T-shirt";
        $products->description = "awesome Red T-shirt";
        $products->price = "69.99";
        $products->quantity = "2";
        $products->category = "shirt";
        $products->type = "man";
        $products->image = "product2.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product3.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product4.webp";
        $products->save(); $products = new Product();
        $products->name = "white T-shirt";
        $products->description = "awesome white T-shirt";
        $products->price = "49.90";
        $products->quantity = "9";
        $products->category = "shirt";
        $products->type = "man";
        $products->image = "product1.webp";
        $products->save();
        $products = new Product();
        $products->name = "Red T-shirt";
        $products->description = "awesome Red T-shirt";
        $products->price = "69.99";
        $products->quantity = "2";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product2.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product3.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product4.webp";
        $products->save();$products = new Product();
        $products->name = "white T-shirt";
        $products->description = "awesome white T-shirt";
        $products->price = "49.90";
        $products->quantity = "9";
        $products->category = "shirt";
        $products->type = "man";
        $products->image = "product1.webp";
        $products->save();
        $products = new Product();
        $products->name = "Red T-shirt";
        $products->description = "awesome Red T-shirt";
        $products->price = "69.99";
        $products->quantity = "2";
        $products->category = "shirt";
        $products->type = "man";
        $products->image = "product2.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product3.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product4.webp";
        $products->save(); $products = new Product();
        $products->name = "white T-shirt";
        $products->description = "awesome white T-shirt";
        $products->price = "49.90";
        $products->quantity = "9";
        $products->category = "shirt";
        $products->type = "man";
        $products->image = "product1.webp";
        $products->save();
        $products = new Product();
        $products->name = "Red T-shirt";
        $products->description = "awesome Red T-shirt";
        $products->price = "69.99";
        $products->quantity = "2";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product2.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product3.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product4.webp";
        $products->save();$products = new Product();
        $products->name = "white T-shirt";
        $products->description = "awesome white T-shirt";
        $products->price = "49.90";
        $products->quantity = "9";
        $products->category = "shirt";
        $products->type = "man";
        $products->image = "product1.webp";
        $products->save();
        $products = new Product();
        $products->name = "Red T-shirt";
        $products->description = "awesome Red T-shirt";
        $products->price = "69.99";
        $products->quantity = "2";
        $products->category = "shirt";
        $products->type = "man";
        $products->image = "product2.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product3.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product4.webp";
        $products->save();
        $products = new Product();
        $products->name = "white T-shirt";
        $products->description = "awesome white T-shirt";
        $products->price = "49.90";
        $products->quantity = "9";
        $products->category = "shirt";
        $products->type = "man";
        $products->image = "product1.webp";
        $products->save();
        $products = new Product();
        $products->name = "Red T-shirt";
        $products->description = "awesome Red T-shirt";
        $products->price = "69.99";
        $products->quantity = "2";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product2.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product3.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product4.webp";
        $products->save();$products = new Product();
        $products->name = "white T-shirt";
        $products->description = "awesome white T-shirt";
        $products->price = "49.90";
        $products->quantity = "9";
        $products->category = "shirt";
        $products->type = "man";
        $products->image = "product1.webp";
        $products->save();
        $products = new Product();
        $products->name = "Red T-shirt";
        $products->description = "awesome Red T-shirt";
        $products->price = "69.99";
        $products->quantity = "2";
        $products->category = "shirt";
        $products->type = "man";
        $products->image = "product2.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product3.webp";
        $products->save();
        $products = new Product();
        $products->name = "Green T-shirt";
        $products->description = "awesome Green T-shirt";
        $products->price = "89.90";
        $products->quantity = "5";
        $products->category = "shirt";
        $products->type = "woman";
        $products->image = "product4.webp";
        $products->save();
    }
}
